SELECT * FROM category;
SELECT * FROM customers;
SELECT * FROM inventory;
SELECT * FROM order_items;
SELECT * FROM shipping
WHERE return_date IS NOT NULL;

-- 1. Top Selling Products
-- Query the top 10 products by total sales value.
-- Challenge: Include product name, total quantity sold, and total sales value.

SELECT 
p.product_name,
SUM(oi.quantity) AS quantity_sold,
ROUND(SUM(oi.total_price)) AS total_sales
FROM orders o
LEFT JOIN products p
ON o.product_id = p.product_id
LEFT JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY p.product_name
ORDER BY 3 DESC
LIMIT 10;

-- 2. Revenue by Category
-- Calculate total revenue generated by each product category.
-- Challenge: Include the percentage contribution of each category to total revenue.

-- category_id, category_name, total_revenue, total_contribution

SELECT
c.category_id,
c.category_name,
ROUND(SUM(oi.total_price)) AS total_revenue,
ROUND(SUM(oi.total_price)/
	(SELECT SUM(total_price) FROM order_items)*100)
	AS total_contribution 
FROM order_items oi
LEFT JOIN products p
ON oi.product_id = p.product_id
LEFT JOIN category c
ON c.category_id = p.category_id
GROUP BY 1,2
ORDER BY 3 DESC;

-- 3. Average Order Value (AOV)
-- Compute the average order value for each customer.
-- Challenge: Include only customers with more than 5 orders.

SELECT
c.customer_id,
c.first_name,
ROUND(SUM(oi.total_price)/COUNT(o.order_id)) AS Average,
COUNT(o.order_id) As Total_Orders
FROM orders o
LEFT JOIN customers c
ON o.customer_id = c.customer_id
LEFT JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY 1,2
HAVING COUNT(o.order_id) > 5;

-- 4. Monthly Sales Trend
-- Query monthly total sales over the past year.
-- Challenge: Display the sales trend, showing current month sales
-- and previous month sales.

-- month, current_month_sale, last_month_sale
WITH monthly_sales AS (
SELECT
DATE_TRUNC('month',o.order_date) AS month,
SUM(oi.total_price) AS current_month_sale
FROM orders o
LEFT JOIN order_items oi
ON o.order_id = oi.order_id
WHERE order_date >= CURRENT_DATE - INTERVAL '1 year'
GROUP BY 1
)
SELECT 
month,
ROUND(current_month_sale),
ROUND(LAG(current_month_sale) OVER(ORDER BY month)) AS last_month_sale
FROM monthly_sales;

-- 5. Customers with No Purchases
-- Find customers who have registered but never placed an order.
-- Challenge: List customer details and the time since their registration.

--Approach 1
SELECT *
FROM customers
WHERE customer_id NOT IN (SELECT DISTINCT customer_id FROM orders);

--Approach 2
SELECT *
FROM customers c
LEFT JOIN orders o 
ON c.customer_id = o.customer_id
WHERE o.customer_id IS NULL

-- 6. Best-Selling Categories by State
-- Identify the best-selling product category for each state.
-- Challenge: Include the total sales for that category within each state.

WITH ranking AS
(
SELECT 
ct.state,
c.category_name,
SUM(oi.total_price),
RANK() OVER(PARTITION BY ct.state ORDER BY SUM(oi.total_price) ASC) as rank
FROM orders o
LEFT JOIN order_items oi
ON o.order_id = oi.order_id
LEFT JOIN products p
ON p.product_id = oi.product_id
LEFT JOIN category c
ON c.category_id = p.category_id
LEFT JOIN customers ct
ON ct.customer_id = o.customer_id
GROUP BY 1,2
)
SELECT *
FROM ranking
WHERE rank = 1;

/*
7. Customer Lifetime Value (CLTV)
Calculate the total value of orders placed by each customer over their lifetime.
Challenge: Rank customers based on their CLTV.
*/

SELECT 
o.customer_id,
c.first_name,
ROUND(SUM(oi.total_price)) AS CLTV,
DENSE_RANK() OVER(ORDER BY SUM(oi.total_price)DESC) AS rank
FROM orders o
LEFT JOIN order_items oi
ON o.order_id = oi.order_id
LEFT JOIN customers c
ON c.customer_id = o.customer_id
GROUP BY 1,2;

/*
8. Inventory Stock Alerts
Query products with stock levels below a certain threshold (e.g., less than 10 units).
Challenge: Include last restock date and warehouse information.
*/

SELECT 
i.inventory_id,
p.product_name,
i.stock,
i.last_stock_date,
i.warehouse_id
FROM inventory i 
LEFT JOIN products p
ON p.product_id = i.product_id
WHERE stock < 10;

/*
9. Shipping Delays
Identify orders where the shipping date is later than 2 days after the order date.
Challenge: Include customer, order details, and delivery provider.
*/

SELECT 
c.first_name,
order_date,
shipping_date,
delivery_status
FROM shipping s
LEFT JOIN orders o 
ON o.order_id = s.order_id
LEFT JOIN customers c
ON c.customer_id = o.customer_id
WHERE shipping_date > order_date + INTERVAL '2 days';

/*
10. Payment Success Rate
Calculate the percentage of successful payments across all orders.
Challenge: Include breakdowns by payment status (e.g., failed, pending).
*/

SELECT 
p.payment_status,
COUNT(*) as total_count,
ROUND(COUNT(*)::numeric/(SELECT COUNT(*) FROM payments)::numeric * 100) AS Average
FROM orders o
LEFT JOIN payments p
ON p.order_id = o.order_id
GROUP BY 1;

/*
11. Top Performing Sellers
Find the top 5 sellers based on total sales value.
Challenge: Include both successful and failed orders, and display their percentage of successful orders.
*/
WITH sales AS (
SELECT
s.seller_id,
s.seller_name,
ROUND(SUM(oi.total_price)) AS total_sale
FROM orders o
LEFT JOIN sellers s
ON s.seller_id = o.seller_id
LEFT JOIN order_items oi
ON oi.order_id = o.order_id
GROUP BY 1,2
ORDER BY 3 DESC
LIMIT 5
),
sale_status AS(
SELECT 
o.seller_id,
ts.seller_name,
o.order_status,
COUNT(*) AS status_count
FROM orders o 
LEFT JOIN sales ts
ON ts.seller_id = o.seller_id
WHERE o.order_status NOT IN('Pending','Returned','Refunded') AND seller_name IS NOT NULL
GROUP BY 1,2,3
)
SELECT 
seller_id,
seller_name,
SUM(CASE WHEN order_status = 'Completed' THEN status_count ELSE 0 END) AS completed_orders,
SUM(CASE WHEN order_status = 'Cancelled' THEN status_count ELSE 0 END) AS Cancelled_orders,
SUM(status_count) AS total_sales,
ROUND(SUM(CASE WHEN order_status = 'Completed' THEN status_count ELSE 0 END)::numeric/SUM(status_count)::numeric * 100) AS Completed_percentage,
ROUND(SUM(CASE WHEN order_status = 'Cancelled' THEN status_count ELSE 0 END)::numeric/SUM(status_count)::numeric * 100) AS Cancelled_percentage
FROM sale_status
GROUP BY 1,2;

/*
12. Product Profit Margin
Calculate the profit margin for each product (difference between price and cost of goods sold).
Challenge: Rank products by their profit margin, showing highest to lowest.
*/

SELECT 
p.product_id,
p.product_name,
ROUND(SUM(oi.total_price - (p.cogs*oi.quantity))) AS Margin
FROM order_items oi
LEFT JOIN products p
ON oi.product_id = p.product_id
GROUP BY 1,2
ORDER BY 3 DESC;

/*
13. Most Returned Products
Query the top 10 products by the number of returns.
Challenge: Display the return rate as a percentage of total units sold for each product.
*/

SELECT
p.product_id,
p.product_name,
COUNT(*) AS total_unit_sold,
SUM(CASE WHEN order_status = 'Returned' THEN 1 ELSE 0 END) AS total_returned,
ROUND(SUM(CASE WHEN order_status = 'Returned' THEN 1 ELSE 0 END)::numeric/COUNT(*)::numeric * 100) AS Percentage
FROM order_items oi
LEFT JOIN products p
ON p.product_id = oi.product_id
LEFT JOIN orders o
ON o.order_id = oi.order_id
GROUP BY 1,2

/*
15. Inactive Sellers
Identify sellers who haven't made any sales in the last 6 months.
Challenge: Show the last sale date and total sales from those sellers.
*/
WITH cte AS (
SELECT *
FROM sellers
WHERE seller_id NOT IN (SELECT seller_id FROM orders WHERE order_date >= CURRENT_DATE - INTERVAL '6 months')
)
SELECT 
o.seller_id,
MAX(o.order_date),
MAX(oi.total_price)
FROM orders AS o
LEFT JOIN cte
ON cte.seller_id = o.seller_id
LEFT JOIN order_items AS oi
ON oi.order_id = o.order_id
GROUP BY 1
ORDER BY 1;