SELECT * FROM category;
SELECT * FROM customers;
SELECT * FROM inventory;
SELECT * FROM order_items;
SELECT * FROM shipping
WHERE return_date IS NOT NULL;

-- 1. Top Selling Products
-- Query the top 10 products by total sales value.
-- Challenge: Include product name, total quantity sold, and total sales value.

SELECT 
p.product_name,
SUM(oi.quantity) AS quantity_sold,
ROUND(SUM(oi.total_price)) AS total_sales
FROM orders o
LEFT JOIN products p
ON o.product_id = p.product_id
LEFT JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY p.product_name
ORDER BY 3 DESC
LIMIT 10;

-- 2. Revenue by Category
-- Calculate total revenue generated by each product category.
-- Challenge: Include the percentage contribution of each category to total revenue.

-- category_id, category_name, total_revenue, total_contribution

SELECT
c.category_id,
c.category_name,
ROUND(SUM(oi.total_price)) AS total_revenue,
ROUND(SUM(oi.total_price)/
	(SELECT SUM(total_price) FROM order_items)*100)
	AS total_contribution 
FROM order_items oi
LEFT JOIN products p
ON oi.product_id = p.product_id
LEFT JOIN category c
ON c.category_id = p.category_id
GROUP BY 1,2
ORDER BY 3 DESC;

-- 3. Average Order Value (AOV)
-- Compute the average order value for each customer.
-- Challenge: Include only customers with more than 5 orders.

SELECT
c.customer_id,
c.first_name,
ROUND(SUM(oi.total_price)/COUNT(o.order_id)) AS Average,
COUNT(o.order_id) As Total_Orders
FROM orders o
LEFT JOIN customers c
ON o.customer_id = c.customer_id
LEFT JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY 1,2
HAVING COUNT(o.order_id) > 5;

-- 4. Monthly Sales Trend
-- Query monthly total sales over the past year.
-- Challenge: Display the sales trend, showing current month sales
-- and previous month sales.

-- month, current_month_sale, last_month_sale
WITH monthly_sales AS (
SELECT
DATE_TRUNC('month',o.order_date) AS month,
SUM(oi.total_price) AS current_month_sale
FROM orders o
LEFT JOIN order_items oi
ON o.order_id = oi.order_id
WHERE order_date >= CURRENT_DATE - INTERVAL '1 year'
GROUP BY 1
)
SELECT 
month,
ROUND(current_month_sale),
ROUND(LAG(current_month_sale) OVER(ORDER BY month)) AS last_month_sale
FROM monthly_sales;

-- 5. Customers with No Purchases
-- Find customers who have registered but never placed an order.
-- Challenge: List customer details and the time since their registration.

--Approach 1
SELECT *
FROM customers
WHERE customer_id NOT IN (SELECT DISTINCT customer_id FROM orders);

--Approach 2
SELECT *
FROM customers c
LEFT JOIN orders o 
ON c.customer_id = o.customer_id
WHERE o.customer_id IS NULL

-- 6. Best-Selling Categories by State
-- Identify the best-selling product category for each state.
-- Challenge: Include the total sales for that category within each state.